-- My Money — reference data
-- Category templates copied into per-user categories on first sign-in.
-- Users can rename/archive/add categories freely afterwards.

insert into public.category_templates (name, parent_name, kind, icon, sort) values
  ('Income',          null, 'income',   'banknote',       0),
  ('Salary',          'Income', 'income', null,           1),
  ('Refunds',         'Income', 'income', null,           2),
  ('Other income',    'Income', 'income', null,           3),
  ('Housing',         null, 'expense',  'home',           10),
  ('Rent',            'Housing', 'expense', null,         11),
  ('Mortgage',        'Housing', 'expense', null,         12),
  ('Household',       'Housing', 'expense', null,         13),
  ('Utilities',       null, 'expense',  'zap',            20),
  ('Energy',          'Utilities', 'expense', null,       21),
  ('Water',           'Utilities', 'expense', null,       22),
  ('Broadband',       'Utilities', 'expense', null,       23),
  ('Mobile',          'Utilities', 'expense', null,       24),
  ('Council tax',     'Utilities', 'expense', null,       25),
  ('Groceries',       null, 'expense',  'shopping-cart',  30),
  ('Eating out',      null, 'expense',  'utensils',       40),
  ('Coffee',          null, 'expense',  'coffee',         50),
  ('Transport',       null, 'expense',  'bus',            60),
  ('Fuel',            'Transport', 'expense', null,       61),
  ('Public transport','Transport', 'expense', null,       62),
  ('Parking',         'Transport', 'expense', null,       63),
  ('Hobbies',         null, 'expense',  'bike',           70),
  ('Travel',          null, 'expense',  'plane',          80),
  ('Health',          null, 'expense',  'heart-pulse',    90),
  ('Fitness',         'Health', 'expense', null,          92),
  ('Pharmacy',        'Health', 'expense', null,          93),
  ('Insurance',       null, 'expense',  'shield',         100),
  ('Subscriptions',   null, 'expense',  'repeat',         110),
  ('Shopping',        null, 'expense',  'shopping-bag',   120),
  ('Clothing',        'Shopping', 'expense', null,        121),
  ('Alcohol',         'Shopping', 'expense', null,        122),
  ('Entertainment',   null, 'expense',  'clapperboard',   130),
  ('Debt repayments', null, 'expense',  'credit-card',    140),
  ('Savings',         null, 'expense',  'piggy-bank',     150),
  ('Transfers',       null, 'transfer', 'arrow-left-right', 160),
  ('Cash withdrawal', null, 'expense',  'wallet',         170),
  ('Fees',            null, 'expense',  'receipt',        180),
  ('Gifts',           null, 'expense',  'gift',           190),
  ('Other',           null, 'expense',  'circle-ellipsis', 200)
on conflict do nothing;
